const MensPants = [
    // Group products (if applicable, you can adjust based on your requirements)
    {
        id: 'b78jsd82-lkd12-a2d3',
        type: 'group',
        gender: 'men',
        category: 'pants',
        name: "Slim Fit Black Pants",
        price: 39.99,
        description: "Slim Fit Black Pants",
        sizes: ['S', 'M', 'L', 'XL'],
        material: 'Cotton',
        brand: 'BrandCo',
        availability: true,
        rating: 4.5,
        reviews: 120,
        image: '/images/products/mc/pantsProducts/group1/s1.avif', // First group image
        multiple: [
            {
                image: '/images/products/mc/pantsProducts/group1/s2.avif' // Second group image
            }
        ]
    },
    {
        id: 'f91kdh83-wdj37-b2r6',
        type: 'group',
        gender: 'men',
        category: 'pants',
        name: "Classic Navy Pants",
        price: 49.99,
        description: "Classic Navy Pants",
        sizes: ['S', 'M', 'L', 'XL'],
        material: 'Linen',
        brand: 'ChicWear',
        availability: true,
        rating: 4.7,
        reviews: 100,
        image: '/images/products/mc/pantsProducts/group2/s1.avif', // Second group image
        multiple: [
            {
                image: '/images/products/mc/pantsProducts/group2/s2.avif' // Second group image
            }
        ]
    },

    // Single products
    {
        id: 'a82shd12-kjs04-d1r9',
        type: 'single',
        gender: 'men',
        category: 'pants',
        name: "Stonewashed Denim Pants",
        price: 59.99,
        description: "Stonewashed Denim Pants",
        sizes: ['S', 'M', 'L', 'XL'],
        material: 'Denim',
        brand: 'UrbanWear',
        availability: true,
        rating: 4.6,
        reviews: 150,
        image: '/images/products/mc/pantsProducts/p (1).avif' // First single image
    },
    {
        id: 'j84fkd23-mlw56-z8p3',
        type: 'single',
        gender: 'men',
        category: 'pants',
        name: "Chino Khaki Pants",
        price: 69.99,
        description: "Chino Khaki Pants",
        sizes: ['S', 'M', 'L', 'XL'],
        material: 'Cotton',
        brand: 'ChicStyles',
        availability: true,
        rating: 4.8,
        reviews: 180,
        image: '/images/products/mc/pantsProducts/p (2).avif' // Second single image
    },
    {
        id: 's92hsk04-wel82-m1k7',
        type: 'single',
        gender: 'men',
        category: 'pants',
        name: "Slim Fit Gray Pants",
        price: 79.99,
        description: "Slim Fit Gray Pants",
        sizes: ['S', 'M', 'L', 'XL'],
        material: 'Wool',
        brand: 'ProStyle',
        availability: true,
        rating: 4.4,
        reviews: 130,
        image: '/images/products/mc/pantsProducts/p (3).avif' // Third single image
    },
    {
        id: 'p39lkj23-fgd98-b1q6',
        type: 'single',
        gender: 'men',
        category: 'pants',
        name: "Luxe Black Leather Pants",
        price: 89.99,
        description: "Luxe Black Leather Pants",
        sizes: ['S', 'M', 'L', 'XL'],
        material: 'Leather',
        brand: 'LuxuryWear',
        availability: true,
        rating: 4.5,
        reviews: 110,
        image: '/images/products/mc/pantsProducts/p (4).avif' 
    },
    {
        id: 'q28wer12-zmn68-j1w9',
        type: 'single',
        gender: 'men',
        category: 'pants',
        name: "Cargo Green Pants",
        price: 39.99,
        description: "Cargo Green Pants",
        sizes: ['S', 'M', 'L', 'XL'],
        material: 'Polyester',
        brand: 'TrendyWear',
        availability: true,
        rating: 4.6,
        reviews: 170,
        image: '/images/products/mc/pantsProducts/p (5).avif' // Fifth single image
    },
    {
        id: 't67sdf19-pgf22-b3r5',
        type: 'single',
        gender: 'men',
        category: 'pants',
        name: "Casual Beige Pants",
        price: 54.99,
        description: "Casual Beige Pants",
        sizes: ['S', 'M', 'L', 'XL'],
        material: 'Linen',
        brand: 'ProStyle',
        availability: true,
        rating: 4.7,
        reviews: 200,
        image: '/images/products/mc/pantsProducts/p (6).avif' // Sixth single image
    },
    {
        id: 'y92dfo13-rfi56-c4p7',
        type: 'single',
        gender: 'men',
        category: 'pants',
        name: "Dark Blue Dress Pants",
        price: 69.99,
        description: "Dark Blue Dress Pants",
        sizes: ['S', 'M', 'L', 'XL'],
        material: 'Silk',
        brand: 'PremiumWear',
        availability: true,
        rating: 4.8,
        reviews: 150,
        image: '/images/products/mc/pantsProducts/p (7).avif' // Seventh single image
    },
    {
        id: 'k27jhx12-pqz56-m2k1',
        type: 'single',
        gender: 'men',
        category: 'pants',
        name: "Winter Wool Pants",
        price: 79.99,
        description: "Winter Wool Pants",
        sizes: ['S', 'M', 'L', 'XL'],
        material: 'Wool',
        brand: 'EliteStyles',
        availability: true,
        rating: 4.3,
        reviews: 140,
        image: '/images/products/mc/pantsProducts/p (8).avif' // Eighth single image
    },
    {
        id: 'n93fkd23-mjv76-t8p9',
        type: 'single',
        gender: 'men',
        category: 'pants',
        name: "Performance Jogger Pants",
        price: 69.99,
        description: "Performance Jogger Pants",
        sizes: ['S', 'M', 'L', 'XL'],
        material: 'Polyester',
        brand: 'SportX',
        availability: true,
        rating: 4.5,
        reviews: 130,
        image: '/images/products/mc/pantsProducts/p (9).avif' // Ninth single image
    },
    {
        id: 'm92hjd13-wsd89-k7w4',
        type: 'single',
        gender: 'men',
        category: 'pants',
        name: "Modern Slim Pants",
        price: 64.99,
        description: "Modern Slim Pants",
        sizes: ['S', 'M', 'L', 'XL'],
        material: 'Denim',
        brand: 'FashionElite',
        availability: true,
        rating: 4.6,
        reviews: 120,
        image: '/images/products/mc/pantsProducts/p (10).avif' // Tenth single image
    },
    {
        id: 'g27hsd15-rfn67-d4l2',
        type: 'single',
        gender: 'men',
        category: 'pants',
        name: "Light Grey Work Pants",
        price: 59.99,
        description: "Light Grey Work Pants",
        sizes: ['S', 'M', 'L', 'XL'],
        material: 'Cotton',
        brand: 'WorkwearX',
        availability: true,
        rating: 4.7,
        reviews: 150,
        image: '/images/products/mc/pantsProducts/p (11).avif' // Eleventh single image
    },
    {
        id: 'b47gkd22-pmw36-x3l1',
        type: 'single',
        gender: 'men',
        category: 'pants',
        name: "Comfort Fit Black Pants",
        price: 49.99,
        description: "Comfort Fit Black Pants",
        sizes: ['S', 'M', 'L', 'XL'],
        material: 'Linen',
        brand: 'ComfyWear',
        availability: true,
        rating: 4.8,
        reviews: 180,
        image: '/images/products/mc/pantsProducts/p (12).avif' // Twelfth single image
    },
    {
        id: 'k72sfh13-nbt58-p2s4',
        type: 'single',
        gender: 'men',
        category: 'pants',
        name: "Burgundy Tapered Pants",
        price: 79.99,
        description: "Burgundy Tapered Pants",
        sizes: ['S', 'M', 'L', 'XL'],
        material: 'Wool',
        brand: 'LuxuryFit',
        availability: true,
        rating: 4.9,
        reviews: 200,
        image: '/images/products/mc/pantsProducts/p (13).avif' // Thirteenth single image
    },
    {
        id: 'q83fjd23-mnb74-p2x9',
        type: 'single',
        gender: 'men',
        category: 'pants',
        name: "Khaki Casual Pants",
        price: 69.99,
        description: "Khaki Casual Pants",
        sizes: ['S', 'M', 'L', 'XL'],
        material: 'Cotton',
        brand: 'CasualWear',
        availability: true,
        rating: 4.6,
        reviews: 170,
        image: '/images/products/mc/pantsProducts/p (14).avif' // Fourteenth single image
    }
];

export default MensPants;
