const MensSweaters = [
    // Grouped products
    {
        id: 'b7f3d2a8-29b7-4b2b-b786-6fe8a90b79f5',
        type: 'group',
        gender: 'men',
        category: 'sweater',
        name: "Chunky Knit Sweater",
        price: 59.99,
        description: "Chunky Knit Sweater",
        sizes: ['S', 'M', 'L', 'XL'],
        material: 'Wool',
        brand: 'KnitCo',
        availability: true,
        rating: 4.5,
        reviews: 120,
        image: '/images/products/mc/sweatersProducts/group1/s1.avif',
        multiple: [
            { image: '/images/products/mc/sweatersProducts/group1/s2.avif' }
        ]
    },
    {
        id: 'b1c2a7d4-7b5d-4cb5-b8b3-60d5d2b3141a',
        type: 'group',
        gender: 'men',
        category: 'sweater',
        name: "Casual Gray Sweater",
        price: 49.99,
        description: "Casual Gray Sweater",
        sizes: ['S', 'M', 'L', 'XL'],
        material: 'Cotton',
        brand: 'UrbanWear',
        availability: true,
        rating: 4.6,
        reviews: 140,
        image: '/images/products/mc/sweatersProducts/group2/s1.avif',
        multiple: [
            { image: '/images/products/mc/sweatersProducts/group2/s2.avif' }
        ]
    },
    {
        id: 'e9b7a65c-e96a-4b9d-b1b5-9c11d09b6a02',
        type: 'group',
        gender: 'men',
        category: 'sweater',
        name: "V-Neck Merino Sweater",
        price: 69.99,
        description: "V-Neck Merino Sweater",
        sizes: ['S', 'M', 'L', 'XL'],
        material: 'Merino Wool',
        brand: 'FashionX',
        availability: true,
        rating: 4.7,
        reviews: 130,
        image: '/images/products/mc/sweatersProducts/group3/s1.avif',
        multiple: [
            { image: '/images/products/mc/sweatersProducts/group3/s2.avif' }
        ]
    },

    // Single products
    {
        id: '6cf0d7ab-24e2-4bfc-b37b-5314f9a20839',
        type: 'single',
        gender: 'men',
        category: 'sweater',
        name: "Chunky Knit Sweater",
        price: 59.99,
        description: "Chunky Knit Sweater",
        sizes: ['S', 'M', 'L', 'XL'],
        material: 'Wool',
        brand: 'KnitCo',
        availability: true,
        rating: 4.5,
        reviews: 120,
        image: '/images/products/mc/sweatersProducts/p (1).avif'
    },
    {
        id: '29a1b8be-d9ac-48fc-8e3e-88f4cb27ec5c',
        type: 'single',
        gender: 'men',
        category: 'sweater',
        name: "Casual Gray Sweater",
        price: 49.99,
        description: "Casual Gray Sweater",
        sizes: ['S', 'M', 'L', 'XL'],
        material: 'Cotton',
        brand: 'UrbanWear',
        availability: true,
        rating: 4.6,
        reviews: 140,
        image: '/images/products/mc/sweatersProducts/p (2).avif'
    },
    {
        id: 'cf79ab7b-fb76-4a8f-9497-d8f72b6b7a63',
        type: 'single',
        gender: 'men',
        category: 'sweater',
        name: "V-Neck Merino Sweater",
        price: 69.99,
        description: "V-Neck Merino Sweater",
        sizes: ['S', 'M', 'L', 'XL'],
        material: 'Merino Wool',
        brand: 'FashionX',
        availability: true,
        rating: 4.7,
        reviews: 130,
        image: '/images/products/mc/sweatersProducts/p (3).avif'
    },
    {
        id: '1f8a9dbe-f72e-4b7b-a85e-e09edb0c1cc6',
        type: 'single',
        gender: 'men',
        category: 'sweater',
        name: "Zippered Hoodie Sweater",
        price: 79.99,
        description: "Zippered Hoodie Sweater",
        sizes: ['S', 'M', 'L', 'XL'],
        material: 'Polyester',
        brand: 'ComfyWear',
        availability: true,
        rating: 4.6,
        reviews: 150,
        image: '/images/products/mc/sweatersProducts/p (4).avif'
    },
    {
        id: '64fc2c5b-f380-47a3-8301-f39db35f6f1a',
        type: 'single',
        gender: 'men',
        category: 'sweater',
        name: "Lightweight Knit Sweater",
        price: 59.99,
        description: "Lightweight Knit Sweater",
        sizes: ['S', 'M', 'L', 'XL'],
        material: 'Cotton',
        brand: 'StreetStyle',
        availability: true,
        rating: 4.8,
        reviews: 160,
        image: '/images/products/mc/sweatersProducts/p (5).avif'
    },
    {
        id: '6a31b238-e31f-44f5-b8e2-f4e585bc169b',
        type: 'single',
        gender: 'men',
        category: 'sweater',
        name: "Cable Knit Sweater",
        price: 69.99,
        description: "Cable Knit Sweater",
        sizes: ['S', 'M', 'L', 'XL'],
        material: 'Wool',
        brand: 'FashionPlus',
        availability: true,
        rating: 4.9,
        reviews: 200,
        image: '/images/products/mc/sweatersProducts/p (6).avif'
    },
    {
        id: 'c9d28394-f289-44ea-a29b-4a8e5c4c3fe3',
        type: 'single',
        gender: 'men',
        category: 'sweater',
        name: "Thermal Knit Sweater",
        price: 89.99,
        description: "Thermal Knit Sweater",
        sizes: ['S', 'M', 'L', 'XL'],
        material: 'Thermal Wool',
        brand: 'ThermaWear',
        availability: true,
        rating: 4.7,
        reviews: 180,
        image: '/images/products/mc/sweatersProducts/p (7).avif'
    },
    {
        id: '682bfe23-569b-49f4-8e9c-b4fdfd464fd0',
        type: 'single',
        gender: 'men',
        category: 'sweater',
        name: "Button-Up Cardigan Sweater",
        price: 79.99,
        description: "Button-Up Cardigan Sweater",
        sizes: ['S', 'M', 'L', 'XL'],
        material: 'Cotton Blend',
        brand: 'ClassicWear',
        availability: true,
        rating: 4.8,
        reviews: 170,
        image: '/images/products/mc/sweatersProducts/p (8).avif'
    },
    {
        id: 'b12cfdcb-52a1-4879-a759-0560cd9e8285',
        type: 'single',
        gender: 'men',
        category: 'sweater',
        name: "Chunky Knit Sweater",
        price: 59.99,
        description: "Chunky Knit Sweater",
        sizes: ['S', 'M', 'L', 'XL'],
        material: 'Wool',
        brand: 'KnitCo',
        availability: true,
        rating: 4.5,
        reviews: 120,
        image: '/images/products/mc/sweatersProducts/p (9).avif'
    },
    {
        id: 'd8f80dbd-c07a-404d-a4e3-e4646c80f9bb',
        type: 'single',
        gender: 'men',
        category: 'sweater',
        name: "Casual Gray Sweater",
        price: 49.99,
        description: "Casual Gray Sweater",
        sizes: ['S', 'M', 'L', 'XL'],
        material: 'Cotton',
        brand: 'UrbanWear',
        availability: true,
        rating: 4.6,
        reviews: 140,
        image: '/images/products/mc/sweatersProducts/p (10).avif'
    },
    {
        id: '7a764b4f-0cde-49ed-b2a7-15e0d8b1e4ed',
        type: 'single',
        gender: 'men',
        category: 'sweater',
        name: "V-Neck Merino Sweater",
        price: 69.99,
        description: "V-Neck Merino Sweater",
        sizes: ['S', 'M', 'L', 'XL'],
        material: 'Merino Wool',
        brand: 'FashionX',
        availability: true,
        rating: 4.7,
        reviews: 130,
        image: '/images/products/mc/sweatersProducts/p (11).avif'
    },
    {
        id: 'f03e2a91-f7f1-4422-92b1-ec7fc5b54598',
        type: 'single',
        gender: 'men',
        category: 'sweater',
        name: "Zippered Hoodie Sweater",
        price: 79.99,
        description: "Zippered Hoodie Sweater",
        sizes: ['S', 'M', 'L', 'XL'],
        material: 'Polyester',
        brand: 'ComfyWear',
        availability: true,
        rating: 4.6,
        reviews: 150,
        image: '/images/products/mc/sweatersProducts/p (12).avif'
    },
    {
        id: 'c6e2e2df-c3fd-4cc2-8b5a-dfdf047e0b70',
        type: 'single',
        gender: 'men',
        category: 'sweater',
        name: "Lightweight Knit Sweater",
        price: 59.99,
        description: "Lightweight Knit Sweater",
        sizes: ['S', 'M', 'L', 'XL'],
        material: 'Cotton',
        brand: 'StreetStyle',
        availability: true,
        rating: 4.8,
        reviews: 160,
        image: '/images/products/mc/sweatersProducts/p (13).avif'
    },
    {
        id: '285a59f7-6a72-4293-b03f-c4b9f1e1ad8e',
        type: 'single',
        gender: 'men',
        category: 'sweater',
        name: "Cable Knit Sweater",
        price: 69.99,
        description: "Cable Knit Sweater",
        sizes: ['S', 'M', 'L', 'XL'],
        material: 'Wool',
        brand: 'FashionPlus',
        availability: true,
        rating: 4.9,
        reviews: 200,
        image: '/images/products/mc/sweatersProducts/p (14).avif'
    }
];

export default MensSweaters;
