const MensShoes = [
    // Grouped products
    {
        id: 'mshoes-9823af19b1c44d5a87e3',
        type: 'group',
        gender: 'men',
        category: 'shoes',
        name: "Sporty Running Shoes",
        price: 89.99,
        description: "Sporty Running Shoes",
        sizes: ['8', '9', '10', '11', '12'],
        material: 'Mesh',
        brand: 'SpeedRun',
        availability: true,
        rating: 4.7,
        reviews: 200,
        image: '/images/products/mc/shoesProducts/group1/s1.avif',
        multiple: [{ image: '/images/products/mc/shoesProducts/group1/s2.avif' }]
    },
    {
        id: 'mshoes-76fb329cde124b50a8d2',
        type: 'group',
        gender: 'men',
        category: 'shoes',
        name: "Leather Formal Shoes",
        price: 129.99,
        description: "Leather Formal Shoes",
        sizes: ['8', '9', '10', '11', '12'],
        material: 'Leather',
        brand: 'StyleWalk',
        availability: true,
        rating: 4.8,
        reviews: 180,
        image: '/images/products/mc/shoesProducts/group2/s1.avif',
        multiple: [{ image: '/images/products/mc/shoesProducts/group2/s2.avif' }]
    },
    {
        id: 'mshoes-1e45d6a7c3b24d08a9f1',
        type: 'group',
        gender: 'men',
        category: 'shoes',
        name: "Casual Loafers",
        price: 79.99,
        description: "Casual Loafers",
        sizes: ['8', '9', '10', '11', '12'],
        material: 'Suede',
        brand: 'UrbanStep',
        availability: true,
        rating: 4.5,
        reviews: 150,
        image: '/images/products/mc/shoesProducts/group3/s1.avif',
        multiple: [{ image: '/images/products/mc/shoesProducts/group3/s2.avif' }]
    },

    // Single products
    {
        id: 'mshoes-a19f823bc48d4207e65c',
        type: 'single',
        gender: 'men',
        category: 'shoes',
        name: "Sporty Running Shoes",
        price: 89.99,
        description: "Sporty Running Shoes",
        sizes: ['8', '9', '10', '11', '12'],
        material: 'Mesh',
        brand: 'SpeedRun',
        availability: true,
        rating: 4.7,
        reviews: 200,
        image: '/images/products/mc/shoesProducts/p (1).avif'
    },
    {
        id: 'mshoes-6f29c4b8e7d145f08a12',
        type: 'single',
        gender: 'men',
        category: 'shoes',
        name: "Leather Formal Shoes",
        price: 129.99,
        description: "Leather Formal Shoes",
        sizes: ['8', '9', '10', '11', '12'],
        material: 'Leather',
        brand: 'StyleWalk',
        availability: true,
        rating: 4.8,
        reviews: 180,
        image: '/images/products/mc/shoesProducts/p (2).avif'
    },
    {
        id: 'mshoes-bc8230d4a67e195f42f3',
        type: 'single',
        gender: 'men',
        category: 'shoes',
        name: "Casual Loafers",
        price: 79.99,
        description: "Casual Loafers",
        sizes: ['8', '9', '10', '11', '12'],
        material: 'Suede',
        brand: 'UrbanStep',
        availability: true,
        rating: 4.5,
        reviews: 150,
        image: '/images/products/mc/shoesProducts/p (3).avif'
    },
    {
        id: 'mshoes-f01d8237c5b94e2a860d',
        type: 'single',
        gender: 'men',
        category: 'shoes',
        name: "Winter Boots",
        price: 149.99,
        description: "Winter Boots",
        sizes: ['8', '9', '10', '11', '12'],
        material: 'Leather',
        brand: 'FrostGuard',
        availability: true,
        rating: 4.6,
        reviews: 190,
        image: '/images/products/mc/shoesProducts/p (4).avif'
    },
    {
        id: 'mshoes-5bc7a981d2304e8f64b0',
        type: 'single',
        gender: 'men',
        category: 'shoes',
        name: "Sports Sneakers",
        price: 79.99,
        description: "Sports Sneakers",
        sizes: ['8', '9', '10', '11', '12'],
        material: 'Mesh',
        brand: 'SportX',
        availability: true,
        rating: 4.3,
        reviews: 140,
        image: '/images/products/mc/shoesProducts/p (5).avif'
    },
    {
        id: 'mshoes-3e7a9d26b5c04812f8c0',
        type: 'single',
        gender: 'men',
        category: 'shoes',
        name: "Slip-On Comfort Shoes",
        price: 69.99,
        description: "Slip-On Comfort Shoes",
        sizes: ['8', '9', '10', '11', '12'],
        material: 'Canvas',
        brand: 'ComfyStep',
        availability: true,
        rating: 4.4,
        reviews: 160,
        image: '/images/products/mc/shoesProducts/p (6).avif'
    }
];

export default MensShoes;
